### ISSUE TITLE
New Item screen - dark theme is not applied

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme#11]
IIRC the pages was created by @recena a while ago, and it uses a different styling scheme.

![image](https://user-images.githubusercontent.com/3000480/83104349-d408e200-a0b8-11ea-8bfa-a8abe94b6d5a.png)

**Comment by timja** [comment]
Mostly fixed by https://github.com/jenkinsci/dark-theme/pull/37, the copy from existing project still needs work
