### ISSUE TITLE
Document that Dark Theme Does not work on IE11

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme#18]
In my case the dark theme does not get applied.

![image](https://user-images.githubusercontent.com/3000480/83133724-92416100-a0e3-11ea-96c8-6aa04abd45ad.png)

# Environment

* Jenkins Core: https://github.com/jenkinsci/jenkins/pull/4752/commits/670b90776b8373576ac51482c2080cba2dba4e1c
* IE:

![image](https://user-images.githubusercontent.com/3000480/83133827-b9982e00-a0e3-11ea-8549-59558b1d0177.png)

**Comment by oleg-nenashev** [comment]
CC @res0nance

**Comment by timja** [comment]
I would consider this invalid, and just requires documenting.

This needs a modern browser, for reference stackoverflow dropped support for IE 11 completely when doing this:

https://stackoverflow.blog/2020/03/31/building-dark-mode-on-stack-overflow/

**Comment by oleg-nenashev** [comment]
I am fine with just documenting the limitation
