### ISSUE TITLE
Full Stage View icon's background is not transparent

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme#21]
IIRC it comes from a Pipeline Plugin

![image](https://user-images.githubusercontent.com/3000480/83154238-2d483400-a100-11ea-90b1-73c81311448c.png)

**Comment by timja** [comment]
Duplicate of https://github.com/jenkinsci/dark-theme/issues/4

**Comment by oleg-nenashev** [comment]
oops
