### ISSUE TITLE
Pipeline Steps Reference - item description fields are not readable

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme#22]
Item description boxes should be dark AFAICT

![image](https://user-images.githubusercontent.com/3000480/83154520-81531880-a100-11ea-8dd4-0d7ed2344efc.png)

**Comment by timja** [comment]
This was fixed by the help fix

![image](https://user-images.githubusercontent.com/21194782/83263468-8b375300-a1b6-11ea-8f6e-1145e2dc3089.png)
