### ISSUE TITLE
Incompatibilities on the credentials plugin

### ISSUE THREAD

**Issue by fqueiruga** [jenkinsci/dark-theme#27]
The cert input fields on the credentials plugin are not compatible with dark mode:

<img width="685" alt="Captura de pantalla 2020-05-28 a las 17 33 25" src="https://user-images.githubusercontent.com/5738588/83163008-c8dea200-a10a-11ea-8590-e6dcb9870eb0.png">

**Comment by timja** [comment]
probably needs similar changes to what I did in passwords.css in jenkins core, (they're basically the same control)

**Comment by timja** [comment]
This is actually hosted in core,

Fixed now:

![image](https://user-images.githubusercontent.com/21194782/83264556-2aa91580-a1b8-11ea-82a9-9284a5609cee.png)
