### ISSUE TITLE
Job configuration is not compatible with dark mode

### ISSUE THREAD

**Issue by fqueiruga** [jenkinsci/dark-theme#28]
The job config form has a light background even with dark mode enable. May have something to do with #11

Example:
<img width="1680" alt="Captura de pantalla 2020-05-28 a las 17 44 44" src="https://user-images.githubusercontent.com/5738588/83163210-10fdc480-a10b-11ea-8113-8c4df2ca3a46.png">

**Comment by timja** [comment]
Not really related to #11, different selectors are applied fixing #11 didn't fix this

**Comment by timja** [comment]
Fixed except for the pipeline widget which is a plugin issue

**Comment by timja** [comment]
Reported pipeline issue in https://github.com/jenkinsci/dark-theme/issues/41

I refactored the 2 widgets to use the same variables mostly, so ended up being related
