### ISSUE TITLE
Text of call-to-action in All Views are not readable because low contrast with the background

### ISSUE THREAD

**Issue by EstherAF** [jenkinsci/dark-theme#31]
A picture is better than a thousand words:

![Screenshot_20200528_211024](https://user-images.githubusercontent.com/5547479/83183483-2df4c080-a128-11ea-9ad0-8cd8062bfd9c.png)

That text with the light blue in the background is not readable.

To reproduce it, just start a jenkins instance from scratch, with the default empty configuration, and go to the main page.

Testing with:

- jenkins-core at branch timja/dark-mode (jenkinsci/jenkins@86c0bd0)
- dark-theme at master (commit f31189f)

**Comment by timja** [comment]
Thanks, not seeing this in my instance as I have ~6 tests jobs.

Should be an easy fix
