### ISSUE TITLE
Incompatibility of the dropdown list of administrative monitors

### ISSUE THREAD

**Issue by EstherAF** [jenkinsci/dark-theme#32]
Screenshot:

![Screenshot_20200528_211824](https://user-images.githubusercontent.com/5547479/83183942-fcc8c000-a128-11ea-8a97-5a03e7e61182.png)

The background of the list of administrative monitors is still white.

Testing with:
- jenkins-core at branch timja/dark-mode (https://github.com/jenkinsci/jenkins/commit/86c0bd01de)
- dark-theme at master (commit https://github.com/jenkinsci/dark-theme/commit/f31189f)

**Comment by timja** [comment]
Fixed

![image](https://user-images.githubusercontent.com/21194782/83265104-f5e98e00-a1b8-11ea-8c5f-92610d5a5cd1.png)
