### ISSUE TITLE
Theme versioning

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme#46]
As documented in https://www.jenkins.io/doc/book/managing/ui-themes/#information-for-theme-developers , it is advised to version the theme so that it can evolve easily while leaving an opportunity for others to use older versions on incompatible instances.

Acceptance criteria

- [ ] - We use GitHub releases and Release Drafter
- [ ] - We deploy versions archive somewhere so that they are accessible to users (github.io or jsdelivr or something else)

**Comment by timja** [comment]
> We deploy versions archive somewhere so that they are accessible to users (github.io or jsdelivr or something else)

js deliver supports tags and pulls directly from github, it's basically zero effort (other than documentation) so I would recommend doing that
