### ISSUE TITLE
Build Executor status uses non-transparent GIF for disconnected agents

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme#47]
Build Executor status uses non-transparent GIF: http://localhost:8080/static/32aff5ee/images/16x16/error.gif 

![image](https://user-images.githubusercontent.com/3000480/83245985-c713ed80-a1a1-11ea-9142-bcf724955801.png)

It could be just replaced by http://localhost:8080/static/32aff5ee/images/16x16/error.png

**Comment by fqueiruga** [comment]
It could also be replaced with an `<l:svgIcon>`!

**Comment by oleg-nenashev** [comment]
@fqueiruga why did you close it? :)

**Comment by fqueiruga** [comment]
Because I'm to clumsy to click the proper comment button :|
