### ISSUE TITLE
Create a Jenkins image and guidelines for testing

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme#6]
It would be great if the users had an opportunity to quickly test the theme with the latest version of the Jenkins core (or a branch) and with the a set of plugins and configurations. I would like to build it on the top of the https://github.com/oleg-nenashev/demo-jenkins-config-as-code demo

**Comment by oleg-nenashev** [comment]
For now we should build it based on https://github.com/jenkinsci/jenkins/pull/4752 .
Work in progress

**Comment by timja** [comment]
Is this complete @oleg-nenashev ?

**Comment by oleg-nenashev** [comment]
I think so. It kinda works. Will need an update once the Jenkins core PRs are merged and released, but good for testing now
