### ISSUE TITLE
Jenkins Core: Login Screen div has a limited height

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme#76]
.... and it leads to white rectangles in the bottom.
https://github.com/jenkinsci/jenkins/pull/4763 does not fix it at the moment

![image](https://user-images.githubusercontent.com/3000480/83351465-7092e480-a344-11ea-97f5-04c9e413febe.png)

**Comment by timja** [comment]
Fixed in https://github.com/oleg-nenashev/jenkins/pull/50
