### ISSUE TITLE
Release 1.0-alpha-1

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme#81]
Jenkins core 2.239 is released, so this theme is no usable with Weekly releases. I suggest releasing the 1.0-alpha-1 version so that we pin the current theme and keep doing changes incrementally with a changelog.

WDYT @timja @fqueiruga ?

**Comment by timja** [comment]
Released https://github.com/jenkinsci/dark-theme/releases/tag/0.0.1
