### ISSUE TITLE
Merge back into upstream / client-side switching?

### ISSUE THREAD

**Issue by lifeofguenter** [jenkinsci/dark-theme#86]
This is an amazing effort and I am very much looking forward to using this.

However: would it maybe make sense to have this part of the standard of Jenkins? E.g. detect browser settings like so: https://davy.dev/darkmode ?

That way we would not need to force users to decide between dark/non-dark mode but either preference will get their way :)

**Comment by timja** [comment]
I'm planning to add a dark mode detection option,

Currently it's non planned to be in the Jenkins core so that it can evolve quicker and also handle plugin specific configuration required

**Comment by timja** [comment]
Created https://github.com/jenkinsci/dark-theme/pull/87
